service: lasertag-bot
useDotenv: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  memorySize: 256
  architecture: arm64
  ecr:
    images:
      app:
        path: ./

functions:
  webhook:
    image: app
    environment:
      NODE_OPTIONS: '--enable-source-maps'
      SENTRY_DSN: ${env:SENTRY_DSN}
      WEBHOOK_BASE: ${env:WEBHOOK_BASE}
      BOT_TOKEN: ${env:BOT_TOKEN}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${env:GOOGLE_SERVICE_ACCOUNT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
      GOOGLE_SPREADSHEET_ID: ${env:GOOGLE_SPREADSHEET_ID}
      TELEGRAM_HOME_CHAT_ID: ${env:TELEGRAM_HOME_CHAT_ID}
      PLAYERS_SHEETS_ID: ${env:PLAYERS_SHEETS_ID}
      GAME_SHEETS_ID: ${env:GAME_SHEETS_ID}
    events:
      - http:
          path: /webhook/${env:BOT_TOKEN}
          method: post