service: lasertag-bot
useDotenv: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  memorySize: 256
  architecture: arm64
  ecr:
    images:
      app:
        path: ./

functions:
  webhook:
    image: app
    environment:
      NODE_OPTIONS: '--enable-source-maps'
      SENTRY_DSN: ${env:SENTRY_DSN}
      WEBHOOK_BASE: ${env:WEBHOOK_BASE}
      BOT_TOKEN: ${env:BOT_TOKEN}
      GOOGLE_API_KEY: ${env:GOOGLE_API_KEY}
      GOOGLE_SPREADSHEET_ID: ${env:GOOGLE_SPREADSHEET_ID}
      START_FROM_ROW: ${env:START_FROM_ROW}
      MAX_ROW_NUMBER: ${env:MAX_ROW_NUMBER}
      NAME_COLUMN: ${env:NAME_COLUMN}
      COUNT_COLUMN: ${env:COUNT_COLUMN}
      RENT_COLUMN: ${env:RENT_COLUMN}
      COMMENT_COLUMN: ${env:COMMENT_COLUMN}
      RATING_COLUMN: ${env:RATING_COLUMN}
      PLACE_AND_TIME_CELLS: ${env:PLACE_AND_TIME_CELLS}
      TELEGRAM_HOME_CHAT_ID: ${env:TELEGRAM_HOME_CHAT_ID}
    events:
      - http:
          path: /webhook/${env:BOT_TOKEN}
          method: post