service: lasertag-bot
useDotenv: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  memorySize: 256
  architecture: arm64
  ecr:
    images:
      app:
        path: ./

functions:
  webhook:
    image: app
    environment:
      NODE_OPTIONS: '--enable-source-maps'
      SENTRY_DSN: ${env:SENTRY_DSN}
      WEBHOOK_BASE: ${env:WEBHOOK_BASE}
      BOT_TOKEN: ${env:BOT_TOKEN}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${env:GOOGLE_SERVICE_ACCOUNT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
      TELEGRAM_HOME_CHAT_ID: ${env:TELEGRAM_HOME_CHAT_ID}

      PLAYERS_DOC_ID: ${env:PLAYERS_DOC_ID}
      PLAYERS_SHEETS_ID: ${env:PLAYERS_SHEETS_ID}

      GAME_DOC_ID: ${env:GAME_DOC_ID}
      GAME_SHEETS_ID: ${env:GAME_SHEETS_ID}

      LINKS_DOC_ID: ${env:LINKS_DOC_ID}
      LINKS_SHEETS_ID: ${env:LINKS_SHEETS_ID}

      ENROLL_DOC_ID: ${env:ENROLL_DOC_ID}
      ENROLL_SHEETS_ID: ${env:ENROLL_SHEETS_ID}
      ENROLL_NAMES_RANGE: ${env:ENROLL_NAMES_RANGE}
      ENROLL_COUNT_RANGE: ${env:ENROLL_COUNT_RANGE}
      ENROLL_RENT_RANGE: ${env:ENROLL_RENT_RANGE}
    events:
      - http:
          path: /webhook/${env:BOT_TOKEN}
          method: post