service: lasertag-bot
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 512

functions:
  lasertag-bot:
    handler: dist/src/index.handler
    events:
      - http:
          path: /webhook/${env:BOT_TOKEN}
          method: post