service: lasertag-bot
useDotenv: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  architecture: arm64
  ecr:
    images:
      app:
        path: ./

functions:
  webhook:
    image: app
    events:
      - http:
          path: /webhook/${env:BOT_TOKEN}
          method: post