service: lasertag-bot
useDotenv: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  memorySize: 256
  architecture: arm64
  timeout: 30
  ecr:
    images:
      app:
        path: ./

functions:
  webhook:
    image: app
    environment:
      WEBHOOK_BASE: ${env:WEBHOOK_BASE}
      BOT_TOKEN: ${env:BOT_TOKEN}

      NODE_OPTIONS: ${env:NODE_OPTIONS}
      SENTRY_DSN: ${env:SENTRY_DSN}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${env:GOOGLE_SERVICE_ACCOUNT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
      TELEGRAM_HOME_CHAT_ID: ${env:TELEGRAM_HOME_CHAT_ID}
      DEFAULT_LOCALE: ${env:DEFAULT_LOCALE}

      PLAYERS_DOC_ID: ${env:PLAYERS_DOC_ID}
      PLAYERS_SHEETS_ID: ${env:PLAYERS_SHEETS_ID}

      GAME_DOC_ID: ${env:GAME_DOC_ID}
      GAME_SHEETS_ID: ${env:GAME_SHEETS_ID}

      LINKS_DOC_ID: ${env:LINKS_DOC_ID}
      LINKS_SHEETS_ID: ${env:LINKS_SHEETS_ID}

      ENROLL_DOC_ID: ${env:ENROLL_DOC_ID}
      ENROLL_SHEETS_ID: ${env:ENROLL_SHEETS_ID}
      ENROLL_NAMES_RANGE: ${env:ENROLL_NAMES_RANGE}
      ENROLL_COUNT_RANGE: ${env:ENROLL_COUNT_RANGE}
      ENROLL_RENT_RANGE: ${env:ENROLL_RENT_RANGE}
      ENROLL_COMMENT_RANGE: ${env:ENROLL_COMMENT_RANGE}

      STATS_DOC_ID: ${env:STATS_DOC_ID}
      STATS_SHEETS_ID: ${env:STATS_SHEETS_ID}
      STATS_TIMEZONE: ${env:STATS_TIMEZONE}

      STORE_DOC_ID: ${env:STORE_DOC_ID}
      STORE_SHEETS_ID: ${env:STORE_SHEETS_ID}

      SKILLS_DOC_ID: ${env:SKILLS_DOC_ID}
      SKILLS_SHEETS_ID: ${env:SKILLS_SHEETS_ID}

      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
      CHATGPT_MODEL: ${env:CHATGPT_MODEL}
    events:
      - http:
          path: /webhook/${env:BOT_TOKEN}
          method: post