export enum ActionKind {
  PROCESSED_OK = 'PROCESSED_OK',
  PROCESSED_NOT_OK = 'PROCESSED_NOT_OK',
  DOCUMENT_LOADED = 'DOCUMENT_LOADED',
  SHEETS_LOADED = 'SHEETS_LOADED',
  UNKNOWN_COMMAND = 'UNKNOWN_COMMAND'
}
