version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  lint:
    docker:
      - image: node:12.14

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

  unit-test:
    docker:
      - image: node:12.14

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - slack/status:
          failure_message: "Deployment to ${CIRCLE_BRANCH} has been failed."
          success_message: "Deployment to ${CIRCLE_BRANCH} has been successful."

workflows:
  lint-and-test:
    jobs:
      - lint
      - unit-test