version: 2.1
# test
jobs:
  deploy-to-node-1:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/app
    steps:
      - run:
          name: Test step
          command: echo test

workflows:
  version: 2.1

  feature-preview:
    jobs:
      - deploy-to-node-1:
          filters:
            branches:
              only:
                - /.*-deploy-to-node-1/
