name: Deploy the branch to AWS by PR comment

on:
  issue_comment:
    types: [created]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create a new deployment branch and push it
        if: contains(github.event.comment.body, 'node1 🚀')
        run: |
          git config --global user.name 'Deployment'
          git config --global user.email 'deployment@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout -b max/test-deploy-to-node-1
          git add .
          git commit -m "Automated report"
          git push -u origin max/test-deploy-to-node-1
